### PR TITLE
Feature/figure description

### PR DESCRIPTION
**Pull request by cmhughes**
Demonstration of figure description for `html` version. 

Not sure if it's worth submitting this upstream to `origin/dev`, it might not even be worth merging this here. See what you think.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
I was just talking with Rob yesterday about this in the MBX support group. It may be preferred to have descriptions for the image elements themselves rather than for figures. At least one reason: a figure with more than one image.

Rob asked me to open https://github.com/rbeezer/mathbook/issues/46.

Looks like so much has been happening on Rob's end that we can't automatically merge even this fairly small change you made. Wonder if we should rethink our flow.

**Comment by cmhughes** [comment]
What kind of a different flow are you thinking?

I'm not sure why this won't merge cleanly; presumably because we've been
merging stuff along the way, and our features haven't been accepted
upstream.

I'd really like omd to succeed, but it feels like we can't get off the
ground. Only 1/5 features has been accepted upstream, so I think a fair bit
of divergence and non-trivial merges is inevitable.

**Comment by Alex-Jordan** [comment]
We should look at the details of the conflict, but I suspect it is not the
lack our other work having been accepted that is the problem. I suspect
that rather it's all the work Rob has done in origin/dev. And then we are
making our features based from origin/dev. And then we are trying to merge
into omd/dev, which not only would add our new feature, but a ton of things
Rob has done in parallel.

We almost always will want the things Rob is adding. They are general
improvements in areas we aren't even thinking about yet. So I wouldn't want
to diverge in a way that leaves that out.

Has Rob said rejected any pull requests yet? I was thinking he just hasn't
had time to review them. In the case of `<quantity>`, he's made suggestions
that I think are good, and I want to follow through on for the sake of omd
as well as mathbook.

On Fri, Feb 6, 2015 at 1:02 PM, cmhughes notifications@github.com wrote:

> What kind of a different flow are you thinking?
> 
> I'm not sure why this won't merge cleanly; presumably because we've been
> merging stuff along the way, and our features haven't been accepted
> upstream.
> 
> I'd really like omd to succeed, but it feels like we can't get off the
> ground. Only 1/5 features has been accepted upstream, so I think a fair bit
> of divergence and non-trivial merges is inevitable.
> 
> On Friday, February 6, 2015, Alex Jordan notifications@github.com wrote:
> 
> > I was just talking with Rob yesterday about this in the MBX support
> > group.
> > It may be preferred to have descriptions for the image elements
> > themselves
> > rather than for figures. At least one reason: a figure with more than one
> > image.
> > 
> > Rob asked me to open rbeezer#46
> > https://github.com/rbeezer/mathbook/issues/46.
> > 
> > Looks like so much has been happening on Rob's end that we can't
> > automatically merge even this fairly small change you made. Wonder if we
> > should rethink our flow.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openmathdocs/mathbook/pull/8#issuecomment-73307710.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openmathdocs/mathbook/pull/8#issuecomment-73311687.

## 

Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by cmhughes** [comment]
I'm gonna close this; it sounds likely that Rob will address this upstream, and it's not vital to OMD development. I plan to update the `README` and merge cleanly so that we can accept updates from `origin/dev` more cleanly. 

My next branch will be multiple objects next to each other.

**Pull request closed without merging**
