### PR TITLE
updated readme file with instructions on how to contribute

### PR DESCRIPTION
**Pull request by cmhughes**
This pull request updates `readme.md` to include our workflow. It should be useful for us in the future if ever we find ourselves wanting to replicate our setup, or for anyone else who would like to contribute.

The following website is useful in previewing git markdown: http://tmpvar.com/markdown.html

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Looks good, but I have one comment about staging. I've started being more targeted with use of `git add`. Instead of using `git add .` (staging _all_ edits and untracked files for commit), I've begun adding only specific files or folders. Sometimes while working on a feature, I'll have created some other files as part of development and testing that I don't care to commit and push up. And yet I still may want to keep them and not delete them. If they never get staged, they persist as I switch branches.  

Also, if I haven't committed a lot along the way, it can sometimes be hard to come up with one commit message for all the changes all at once at the end. Staging one file at a time and committing with a message that relates to that one file lets me feel more informative with my commit messages.

Anyway it may be a good idea not to promote using `git add .` so much. Maybe say something like `git add <new files and edited files>`?

I am running out the door now. Please feel free to merge this.

**Comment by cmhughes** [comment]
Good points, well made. I've made some updates--have a look and see what you think; do feel free to make other changes that you'd like to see.

I'm in no rush to merge this, so feel free to do so later on :)

**Comment by cmhughes** [comment]
Awesome, thanks for reviewing and accepting this.

So far, is this the process that you envisaged?

**Comment by Alex-Jordan** [comment]
Yep! And then once we are done bringing our additions and edit over to
omd/mathbook, we can look into trimming the xsl out of omd/precalc.

On Sun, Jan 25, 2015 at 11:55 PM, cmhughes notifications@github.com wrote:

> Awesome, thanks for reviewing and accepting this.
> 
> So far, is this the process that you envisaged?
> 
> On Sunday, January 25, 2015, Alex Jordan notifications@github.com
> wrote:
> 
> > Merged #5 https://github.com/openmathdocs/mathbook/pull/5.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openmathdocs/mathbook/pull/5#event-224375954.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openmathdocs/mathbook/pull/5#issuecomment-71424471.

## 

Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by cmhughes** [comment]
Yes, that's inline with what I was thinking too :) git is truly a wonderful
tool

**Comment by cmhughes** [comment]
We've merged this successfully into our `openmathdocs/dev` branch, and we won't be submitting it to `MBX`, so I'm deleting this branch.

**Pull request merged**
